---
title: "Untitled"
author: "Gabriel Kahn"
date: "April 30, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Import and Clean Data

```{r}

state_data <- read_csv("NCHS_-_Drug_Poisoning_Mortality_by_State__United_States.csv")

state_data
```

```{r}
county_data <- read_csv("NCHS_-_Drug_Poisoning_Mortality_by_County__United_States.csv")

country_data <- county_data %>% 
    mutate(
    # Turn death rate into an ordered factor
    Estimated_Age_Adjusted_Death_Rate = factor(Estimated_Age_Adjusted_Death_Rate, 
                                                     levels = c("<2", "2-3.9", "4-5.9",
                                           "6-7.9", "8-9.9", "10-11.9",
                                           "12-13.9", "14-15.9", "16-17.9",
                                           "18-19.9", "20-21.9", "22-23.9",
                                           "24-25.9", "26-27.9", "28-29.9",
                                           "30+")))
country_data
```

# Exploring the Data

```{r}
# this graph is too busy but facters are good
county_data %>% 
  filter(Year == 2016) %>% 

ggplot(aes(log(Population), Estimated_Age_Adjusted_Death_Rate, facet = State)) +
  geom_point() +
  facet_wrap(~State)
```




```{r}
# this graph is too busy but facters are good
state_data %>% 
  filter(Year == 2016) %>% 

ggplot(aes(log(Population), Estimated_Age_Adjusted_Death_Rate, facet = State)) +
  geom_point() +
  facet_wrap(~State)
```

```{r}
#put graph of swing states, color by year

swing_states <- county_data %>% 
  filter(State == "Nevada" | State == "Florida" | State == "Colorado" | State ==
         "Ohio" | State == "New Hampshire") %>% 
  filter(Year == 2016)

swing_states
```

```{r}
ggplot(swing_states, aes(log(Population), Estimated_Age_Adjusted_Death_Rate, facet = State )) +
  geom_point()+
  facet_wrap(~State)

```